export { navbarLink } from "./navbarLink";
export { categoriaLink } from "./categoriaLink";
export { promoCards } from "./promoCards";
export { tabsLink } from "./tabsLink";
export { heroLink } from "./heroLink";
export { productDetal } from "./productDetal";
export { productCityName } from "./productCityName";
export { footerBottomLinks } from "./footerBottomLinks";
export { footerCategory } from "./footerCategory";
